### ISSUE TITLE
Rename entities feature causes many problems and doesn't work correctly

### ISSUE THREAD

**Issue by SuperCoder7979** [QuiltMC/quiltflower#112]
Rename entities is an old feature with many bugs. As there are a lot of bugs, this issue will track them:
- [ ] Fields and method definitions aren't renamed properly
- [ ] Inner classes aren't run with the renamer
- [ ] Renamer too strict on what classes should be renamed
- [ ] Renaming certain classes fails to output them

**Comment by DiamondMiner88** [comment]
Additionally documenting here; inner classes of renamed parents are not inlined with rename entities enabled and are instead written to a separate file. However, references to them seem to be ok so it's not too high priority.
