### ISSUE TITLE
Pattern matching tracking issue

### ISSUE THREAD

**Issue by SuperCoder7979** [QuiltMC/quiltflower#157]
We need to do some structural changes for pattern matching in QF. Here's the gist of it:
- [ ] refactor patterns into a `PatternExprent`
- [ ] Add a more generic way to describe patterns in SForms
- [ ] Subclass PatternExprent for type, record, and array patterns
- [ ] Merge #156 so that SForms can understand switch patterns

**Comment by jaskarth** [comment]
It's done.
